[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  from = "/license"
  to = "/license.html"
  status = 200
  force = true

[[redirects]]
  from = "/license/"
  to = "/license.html"
  status = 200
  force = true

[[redirects]]
  from = "/LICENSE"
  to = "/license.html"
  status = 200
  force = true
